# Generated by Django 2.2 on 2024-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='catID',
            field=models.CharField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
