# Generated by Django 2.2 on 2024-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_catid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentID',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
