# Generated by Django 2.2 on 2024-03-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_cat_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cat_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
