# Generated by Django 2.2 on 2024-03-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_cat_cat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
